[package]
name = "pihelper"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pihelper"

[lib]
name = "pihelper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
